# DataSource
spring:
  datasource:
    url: jdbc:h2:./h2db/db;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=TRUE
    driver-class-name: org.h2.Driver
    username: sa
    password:
    # connection pool use tomcat
    tomcat:
      max-active: 10
      max-idle: 10
      min-idle: 10
      initial-size: 5
  # H2 config
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        trace: false
        web-allow-others: false
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  # static resource path
  resources:
    static-locations: classpath:/client-app/dist/
server:
  servlet:
    context-path: /
  port: 8080
