spring:
  # DataSource
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/spring-sec?serverTimezone=UTC
    username: root
    password: root
    # connection pool use tomcat
    tomcat:
      max-active: 10
      max-idle: 10
      min-idle: 10
      initial-size: 5
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  # static resource path
  resources:
    static-locations: classpath:/client-app/dist/
server:
  servlet:
    context-path: /
  port: 8080
